### ISSUE TITLE
Safe mode not reflected by device attribute

### ISSUE THREAD

**Issue by kennethlimcp** [spark/cloud#13]
When a device is in safe mode, a user should be able to know it is in safe mode by polling the device status endpoint.

The current attribute in safe mode: 

```
{ id: '1234567890',
  name: 'duo',
  last_app: null,
  last_ip_address: 'x.x.x.x',
  last_heard: '2016-09-22T23:53:10.924Z',
  product_id: 88,
  connected: true,
  platform_id: 88,
  cellular: false,
  status: 'normal',
  variables: {},
  functions: [] }
```
### Expected behavior

It should be like `status: 'safe-mode` rather than `normal`

**Comment by brycekahle** [comment]
@kennethlimcp Do you have reproduction steps? I just checked a device I know is in safe mode, and it has the correct `status` value.

**Comment by kennethlimcp** [comment]
@brycekahle i placed my devices in safe-mode and looked at `https://api.particle.io/v1/devices?access_token=`. All showed `normal` for `status`
