### ISSUE TITLE
[Web IDE] Included libraries can't be removed

### ISSUE THREAD

**Issue by ScruffR** [spark/cloud#16]
There are several formatting issues with Web IDE that cause the "remove library" button to be unavailable
e.g. https://community.particle.io/t/spark-dallas-temperature-library-not-compiling-and-cannot-remove-it/28843/6

Parallel issue in the Particle Dev repo
https://github.com/spark/particle-dev/issues/180

**Comment by GregSawin** [comment]
Seems to be fixed now

**Comment by stefan-moraru** [comment]
Fixed
