### ISSUE TITLE
Webhooks with incremented names trigger the original webhook

### ISSUE THREAD

**Issue by rps** [spark/cloud#22]
## Bug
Calling a webhook with an incremented name (e.g. `name2` or `name_b`) will cause the original webhook (e.g. `name`) to trigger as well.

### Expected behavior

Only `hook-sent/name2` should occur

### Observed behavior

`hook-sent/name2` occurs twice, and returned data for the second occurrence matches that expected for `name`

### Steps to reproduce

1) Create a webhook with a `generic_name`
2) Create another webhook with an incremented `generic_name2`
3) Publish `generic_name2` event and examine hooks-sent and hook-responses received

**Comment by brycekahle** [comment]
This is intended behavior. Our event system works on prefix filters. You need to use unique prefixes if you want to keep the webhooks separate.
