### ISSUE TITLE
No error message when renaming a device to a name that already exists

### ISSUE THREAD

**Issue by monkbroc** [spark/cloud#3]
### Expected behavior

When renaming a device to a name that already exists for the current user I expect an error message that tells me why the rename failed.

### Observed behavior

The rename failed with an empty error array.

### Steps to reproduce

```
curl -X PUT https://api.particle.io/v1/devices/123 -d name=name_exists -d access_token=abc
{
  "ok": false,
  "code": 403,
  "errors": [
    {}
  ]
}
```

**Comment by brycekahle** [comment]
Fixed in latest release
