### ISSUE TITLE
Unable to upload product firmware using cloud API, unexpected field error

### ISSUE THREAD

**Issue by rickkas7** [spark/cloud#33]
### Expected behavior

I don't seem to be able to use the Cloud API for uploading a product firmware binary as [described here](https://docs.particle.io/reference/api/#upload-product-firmware). I get an unexpected field error.

### Observed behavior

If I pass what I believe to be a valid request, I get an unexpected field error:

```
$ curl -X POST "https://api.particle.io/v1/products/1319/firmware?access_token=1234" -F file=@13subscribetest.bin -F version=25 -F title="cloud upload test"
{"ok":false,"error":"Unexpected field"}
```

### Steps to reproduce

If I leave the "file" field out, then I get an error that it must be specified:

```
$ curl -X POST "https://api.particle.io/v1/products/1319/firware?access_token=1234" -F version=25 -F title="cloud upload test"
{"ok":false,"code":400,"error":"You must specify a file"}
```

**Comment by monkbroc** [comment]
Nice find! I had to dig through the API code to figure out that the correct parameter name is `binary` not `file`. I'll update the docs.
