### ISSUE TITLE
Particle Console doesn't display the value FALSE for boolean Cloud Variables

### ISSUE THREAD

**Issue by davidorser** [spark/cloud#39]
## Bug
The Particle Console doesn't display the value FALSE for boolean Cloud Variables.
(It does display TRUE, when a boolean cloud variable is true.)

### Expected behavior
Should display FALSE when the variable is retrieved.

### Observed behavior
Click Get variable on Particle Console, returns blank.

### Steps to reproduce
Create a registered variable of the Boolean type, attempt to view it on the Particle Console.

**Comment by stefan-moraru** [comment]
Fixed, Console displays "false" now.
