### ISSUE TITLE
Dashboard blank under chromium in Ubuntu

### ISSUE THREAD

**Issue by BasedOnTechnology** [spark/cloud#5]
The entire dashboard/devices panel is completely blank when viewing it from a chromium browser on ubuntu. I've tried clearing cookies, logging out, etc to no avail.

Chromium gives me the following errors in javascript on the dashboard page (redacted):

`Uncaught ReferenceError: define is not defined (anonymous function)	@	dashboard
Failed to find a valid digest in the 'integrity' attribute for resource 'https://dashboard.particle.io/assets/vendor-<redacted>.js' with computed SHA-256 integrity '<redacted>'. The resource has been blocked.`

**Comment by brycekahle** [comment]
Do you have a proxy/extension/anti-virus that might be modifying content? That error is saying the `vendor-xxx.js` script as loaded does not match the integrity hash pre-computed by our server.

**Comment by BasedOnTechnology** [comment]
Oh, yeah, that could definitely be it. I'll test it without extensions in a minute...sorry for wasting your time if it is the problem.

**Comment by brycekahle** [comment]
@BasedOnTechnology any news? Was it extensions?

**Comment by BasedOnTechnology** [comment]
@brycekahle Sorry about the delay, didn't have access to the offending laptop. 

Nope, it doesn't seem to be extensions. I disabled every one, and it's still just giving me a blank page. Would it help if I sent the apparently corrupt .js file to you?

**Comment by brycekahle** [comment]
Unfortunately the file won't help. Are you on a network that has a proxy server or something that might be tampering with data? Can you try a different network?

**Comment by BasedOnTechnology** [comment]
(Sorry about the delay again, I'm so slow). Ok, I tried it on a seperate network, same issue.

I noticed that under Firefox on the same computer under linux, I have no problems. It seems it's just related to chromium, perhaps only even this version. I'll try updating and check back.

**Comment by BasedOnTechnology** [comment]
It's gotta just be this one laptop's chromium installation. Chromium on my desktop loads the dashboard just fine.

Sorry for wasting your time!
