### ISSUE TITLE
[Web IDE] Project order dev view vs. include library in project

### ISSUE THREAD

**Issue by ScruffR** [spark/cloud#50]
Recently someone finally told Web IDE to sort the stored projects alphabetically, which is a good thing, ***but*** that's only the case in the normal development view
![image|200x400](https://user-images.githubusercontent.com/6604878/43444039-0068d608-94a3-11e8-9924-7d1c7a9cdf91.png)
However when trying to include a library in an app, Web IDE presents a "unsorted" list
![image|200x400](https://user-images.githubusercontent.com/6604878/43444074-27b6753a-94a3-11e8-9955-f8c212a11f1c.png)

This is confusing.

BTW, when one tries to import a library ***while*** working on a project, chances are that the library should be includen in ***exactly that*** project, so the extra step to select the target project is rather superfluous and annoying IMO.

**Comment by rickkas7** [comment]
I agree. I don't see a use case for working on a project, going to add a library, and deciding to add it to a different project.

**Comment by stefan-moraru** [comment]
Deployed a fix for this, the list should be sorted.
