### ISSUE TITLE
[Console/Integrations] Add hint that `event` is treated as prefix

### ISSUE THREAD

**Issue by ScruffR** [spark/cloud#51]
While the [Webhook reference docs](https://docs.particle.io/reference/webhooks/#event) do clearly state that the "event name" is treated as prefix, the respective  tooltip is missing that detail

![image](https://user-images.githubusercontent.com/6604878/43517221-38ebb14a-9588-11e8-85d6-106ad1f648d2.png)
 
Adding a respective "footnote" in the [Webhooks guide docs](https://docs.particle.io/guide/tools-and-features/webhooks/#create-the-webhook) (and [here](https://docs.particle.io/guide/tools-and-features/webhooks/#webhook-firmware)) would be good too.

**Comment by monkbroc** [comment]
That's a good suggestion. Thanks.

**Comment by stefan-moraru** [comment]
Thanks to Julien for implementing the fix, which is now live

![image](https://user-images.githubusercontent.com/14219325/44584711-8314dd00-a7b2-11e8-8d93-a2627f9ccfe6.png)
