### ISSUE TITLE
Console enhancement: Add "Signal" device functionality like available in Web IDE

### ISSUE THREAD

**Issue by bloukingfisher** [spark/cloud#54]
I’d love to see the “Signal” device functionality that is in Web IDE available in the Console, particularly for Product devices.

Product devices (that is, unclaimed or claimed by customers) are not available in Web IDE. When a customer may have multiple devices, or, during manufacturing devices get messed up the signal function can help isolate a device or confirm that we’re looking at the right device.

**Comment by monkbroc** [comment]
Thanks for the suggestion. We're adding this to our feature list.

**Comment by monkbroc** [comment]
This is now available in the Console
