### ISSUE TITLE
No error message when claiming a device owned by someone else

### ISSUE THREAD

**Issue by monkbroc** [spark/cloud#7]
### Expected behavior

When claiming a device owned by someone else, previously the API would return as part of the `errors` JSON array the string "That belongs to someone else". The CLI used that to show the prompt to request a transfer.

### Observed behavior

When the device ID is owned by the current user, or is invalid, a 404 response with this body is returned
```
{ ok: false, errors: [ {} ] }
```

This causes the CLI to say `Failed to claim device, server said: [object Object]` since errors contains an empty object instead of a string.

### Steps to reproduce

`particle device add 11111111111111111111111`

**Comment by brycekahle** [comment]
The 404 might be because `11111111111111111111111` is not a valid device id?

**Comment by brycekahle** [comment]
Ok. Confirmed this is an issue. Looking into a fix now
